spring:
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#Dev specific Logging
logging:
  level:
    com.stephensalano.fileflow_api: DEBUG
    org.springframework.security: DEBUG
